import React from 'react';
export const metadata = {
  title: "Login | Dragon News",
  description: "Generated by create next app",
};
const Layout = ({children}) => {
    return (
        <div>
            {children}
        </div>
    );
}

export default Layout;
